name: "Scorecard Analysis"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
 #   - cron: "42 9 * * 0"

env:
  DISPLAY: ":99.0" # Set a display for Xvfb

jobs:
  analyze:
    name: Analyze (Java)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        options: -e VNC_SERVER=true -e VNC_PORT=5900

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Xvfb
        run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          build-mode: autobuild
          queries: +security-extended,security-and-quality

      - name: Build with Gradle
        run: gradle build -Djava.awt.headless=true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      - name: Run Scorecard Analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          format: sarif
          publish_results: true

      - name: Upload Scorecard Results
        uses: actions/upload-artifact@v4
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - name: Upload SARIF results to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
